## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])

In [3]:
# Determine the number of unique values in each column.
unique_value_counts = application_df.nunique()
print(unique_value_counts)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_type_counts)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value for binning
cutoff_value = 500  # You can adjust this value as needed

# Create a list of application types to be replaced with "Other"
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

# Check to make sure binning was successful
print(application_df['APPLICATION_TYPE'].value_counts())

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_gt1 = classification_counts[classification_counts > 1]
print(classification_counts_gt1)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value for binning
cutoff_value = 1883  # You can adjust this value as needed

# Create a list of classifications to be replaced with "Other"
classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, "Other")

# Check to make sure binning was successful
print(application_df['CLASSIFICATION'].value_counts())

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_encoded = pd.get_dummies(application_df)

In [10]:
# Split our preprocessed data into our features and target arrays
X = application_df_encoded.drop(columns=['IS_SUCCESSFUL'])
y = application_df_encoded['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation='relu', input_dim=X_train_scaled.shape[1]))


# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [14]:
# Train the model with Early Stopping
nn.fit(X_train_scaled, y_train, epochs=100, verbose=2)

Epoch 1/100
804/804 - 2s - loss: 0.5699 - accuracy: 0.7216 - 2s/epoch - 2ms/step
Epoch 2/100
804/804 - 1s - loss: 0.5572 - accuracy: 0.7288 - 942ms/epoch - 1ms/step
Epoch 3/100
804/804 - 1s - loss: 0.5539 - accuracy: 0.7283 - 932ms/epoch - 1ms/step
Epoch 4/100
804/804 - 1s - loss: 0.5521 - accuracy: 0.7313 - 985ms/epoch - 1ms/step
Epoch 5/100
804/804 - 1s - loss: 0.5510 - accuracy: 0.7309 - 936ms/epoch - 1ms/step
Epoch 6/100
804/804 - 1s - loss: 0.5499 - accuracy: 0.7312 - 980ms/epoch - 1ms/step
Epoch 7/100
804/804 - 1s - loss: 0.5493 - accuracy: 0.7319 - 930ms/epoch - 1ms/step
Epoch 8/100
804/804 - 1s - loss: 0.5480 - accuracy: 0.7323 - 1s/epoch - 1ms/step
Epoch 9/100
804/804 - 1s - loss: 0.5481 - accuracy: 0.7327 - 938ms/epoch - 1ms/step
Epoch 10/100
804/804 - 1s - loss: 0.5475 - accuracy: 0.7317 - 962ms/epoch - 1ms/step
Epoch 11/100
804/804 - 1s - loss: 0.5469 - accuracy: 0.7347 - 952ms/epoch - 1ms/step
Epoch 12/100
804/804 - 1s - loss: 0.5469 - accuracy: 0.7334 - 921ms/epoch - 1ms/step
Epoch 13/100
804/804 - 1s - loss: 0.5459 - accuracy: 0.7337 - 923ms/epoch - 1ms/step
Epoch 14/100
804/804 - 1s - loss: 0.5454 - accuracy: 0.7348 - 959ms/epoch - 1ms/step
Epoch 15/100
804/804 - 1s - loss: 0.5455 - accuracy: 0.7349 - 1s/epoch - 1ms/step
Epoch 16/100
804/804 - 1s - loss: 0.5454 - accuracy: 0.7349 - 981ms/epoch - 1ms/step
Epoch 17/100
804/804 - 1s - loss: 0.5447 - accuracy: 0.7352 - 952ms/epoch - 1ms/step
Epoch 18/100
804/804 - 1s - loss: 0.5445 - accuracy: 0.7365 - 899ms/epoch - 1ms/step
Epoch 19/100
804/804 - 1s - loss: 0.5443 - accuracy: 0.7342 - 949ms/epoch - 1ms/step
Epoch 20/100
804/804 - 1s - loss: 0.5434 - accuracy: 0.7355 - 1s/epoch - 1ms/step
Epoch 21/100
804/804 - 1s - loss: 0.5433 - accuracy: 0.7370 - 1s/epoch - 1ms/step
Epoch 22/100
804/804 - 1s - loss: 0.5433 - accuracy: 0.7348 - 1s/epoch - 1ms/step
Epoch 23/100
804/804 - 1s - loss: 0.5429 - accuracy: 0.7361 - 1s/epoch - 1ms/step
Epoch 24/100
804/804 - 1s - loss: 0.5427 - accuracy: 0.7365 - 1s/epoch - 1ms/step
Epoch 25/100
804/804 - 1s - loss: 0.5428 - accuracy: 0.7368 - 1s/epoch - 1ms/step
Epoch 26/100
804/804 - 1s - loss: 0.5426 - accuracy: 0.7372 - 1s/epoch - 1ms/step
Epoch 27/100
804/804 - 1s - loss: 0.5422 - accuracy: 0.7372 - 966ms/epoch - 1ms/step
Epoch 28/100
804/804 - 1s - loss: 0.5427 - accuracy: 0.7371 - 991ms/epoch - 1ms/step
Epoch 29/100
804/804 - 1s - loss: 0.5420 - accuracy: 0.7372 - 1s/epoch - 1ms/step
Epoch 30/100
804/804 - 1s - loss: 0.5416 - accuracy: 0.7370 - 1s/epoch - 1ms/step
Epoch 31/100
804/804 - 1s - loss: 0.5416 - accuracy: 0.7371 - 1s/epoch - 1ms/step
Epoch 32/100
804/804 - 1s - loss: 0.5412 - accuracy: 0.7372 - 1s/epoch - 1ms/step
Epoch 33/100
804/804 - 1s - loss: 0.5408 - accuracy: 0.7379 - 1s/epoch - 1ms/step
Epoch 34/100
804/804 - 1s - loss: 0.5413 - accuracy: 0.7385 - 1s/epoch - 1ms/step
Epoch 35/100
804/804 - 1s - loss: 0.5412 - accuracy: 0.7374 - 1s/epoch - 1ms/step
Epoch 36/100
804/804 - 1s - loss: 0.5408 - accuracy: 0.7382 - 1s/epoch - 1ms/step
Epoch 37/100
804/804 - 1s - loss: 0.5403 - accuracy: 0.7394 - 1s/epoch - 1ms/step
Epoch 38/100
804/804 - 1s - loss: 0.5407 - accuracy: 0.7379 - 1s/epoch - 1ms/step
Epoch 39/100
804/804 - 1s - loss: 0.5403 - accuracy: 0.7383 - 920ms/epoch - 1ms/step
Epoch 40/100
804/804 - 1s - loss: 0.5403 - accuracy: 0.7379 - 927ms/epoch - 1ms/step
Epoch 41/100
804/804 - 1s - loss: 0.5405 - accuracy: 0.7382 - 907ms/epoch - 1ms/step
Epoch 42/100
804/804 - 1s - loss: 0.5395 - accuracy: 0.7378 - 943ms/epoch - 1ms/step
Epoch 43/100
804/804 - 1s - loss: 0.5400 - accuracy: 0.7383 - 968ms/epoch - 1ms/step
Epoch 44/100
804/804 - 1s - loss: 0.5399 - accuracy: 0.7383 - 1s/epoch - 1ms/step
Epoch 45/100
804/804 - 1s - loss: 0.5396 - accuracy: 0.7386 - 980ms/epoch - 1ms/step
Epoch 46/100
804/804 - 1s - loss: 0.5396 - accuracy: 0.7381 - 925ms/epoch - 1ms/step
Epoch 47/100
804/804 - 1s - loss: 0.5394 - accuracy: 0.7390 - 903ms/epoch - 1ms/step
Epoch 48/100
804/804 - 1s - loss: 0.5398 - accuracy: 0.7383 - 920ms/epoch - 1ms/step
Epoch 49/100
804/804 - 1s - loss: 0.5391 - accuracy: 0.7380 - 935ms/epoch - 1ms/step
Epoch 50/100
804/804 - 1s - loss: 0.5389 - accuracy: 0.7393 - 928ms/epoch - 1ms/step
Epoch 51/100
804/804 - 1s - loss: 0.5391 - accuracy: 0.7392 - 946ms/epoch - 1ms/step
Epoch 52/100
804/804 - 1s - loss: 0.5393 - accuracy: 0.7385 - 927ms/epoch - 1ms/step
Epoch 53/100
804/804 - 1s - loss: 0.5390 - accuracy: 0.7395 - 962ms/epoch - 1ms/step
Epoch 54/100
804/804 - 1s - loss: 0.5382 - accuracy: 0.7381 - 949ms/epoch - 1ms/step
Epoch 55/100
804/804 - 1s - loss: 0.5388 - accuracy: 0.7384 - 1s/epoch - 1ms/step
Epoch 56/100
804/804 - 1s - loss: 0.5388 - accuracy: 0.7390 - 1s/epoch - 1ms/step
Epoch 57/100
804/804 - 1s - loss: 0.5385 - accuracy: 0.7394 - 943ms/epoch - 1ms/step
Epoch 58/100
804/804 - 1s - loss: 0.5380 - accuracy: 0.7389 - 936ms/epoch - 1ms/step
Epoch 59/100
804/804 - 1s - loss: 0.5383 - accuracy: 0.7394 - 936ms/epoch - 1ms/step
Epoch 60/100
804/804 - 1s - loss: 0.5379 - accuracy: 0.7398 - 938ms/epoch - 1ms/step
Epoch 61/100
804/804 - 1s - loss: 0.5384 - accuracy: 0.7393 - 964ms/epoch - 1ms/step
Epoch 62/100
804/804 - 1s - loss: 0.5384 - accuracy: 0.7386 - 935ms/epoch - 1ms/step
Epoch 63/100
804/804 - 1s - loss: 0.5382 - accuracy: 0.7387 - 1s/epoch - 1ms/step
Epoch 64/100
804/804 - 1s - loss: 0.5374 - accuracy: 0.7390 - 953ms/epoch - 1ms/step
Epoch 65/100
804/804 - 1s - loss: 0.5375 - accuracy: 0.7387 - 989ms/epoch - 1ms/step
Epoch 66/100
804/804 - 1s - loss: 0.5380 - accuracy: 0.7399 - 967ms/epoch - 1ms/step
Epoch 67/100
804/804 - 1s - loss: 0.5374 - accuracy: 0.7400 - 934ms/epoch - 1ms/step
Epoch 68/100
804/804 - 1s - loss: 0.5376 - accuracy: 0.7396 - 1s/epoch - 1ms/step
Epoch 69/100
804/804 - 1s - loss: 0.5373 - accuracy: 0.7400 - 1s/epoch - 1ms/step
Epoch 70/100
804/804 - 1s - loss: 0.5371 - accuracy: 0.7388 - 1s/epoch - 1ms/step
Epoch 71/100
804/804 - 1s - loss: 0.5379 - accuracy: 0.7401 - 966ms/epoch - 1ms/step
Epoch 72/100
804/804 - 1s - loss: 0.5372 - accuracy: 0.7398 - 983ms/epoch - 1ms/step
Epoch 73/100
804/804 - 1s - loss: 0.5369 - accuracy: 0.7399 - 1s/epoch - 1ms/step
Epoch 74/100
804/804 - 1s - loss: 0.5372 - accuracy: 0.7390 - 1s/epoch - 1ms/step
Epoch 75/100
804/804 - 1s - loss: 0.5373 - accuracy: 0.7397 - 1s/epoch - 1ms/step
Epoch 76/100
804/804 - 1s - loss: 0.5369 - accuracy: 0.7398 - 1s/epoch - 1ms/step
Epoch 77/100
804/804 - 1s - loss: 0.5369 - accuracy: 0.7399 - 1s/epoch - 1ms/step
Epoch 78/100
804/804 - 1s - loss: 0.5368 - accuracy: 0.7395 - 1s/epoch - 1ms/step
Epoch 79/100
804/804 - 1s - loss: 0.5375 - accuracy: 0.7401 - 993ms/epoch - 1ms/step
Epoch 80/100
804/804 - 1s - loss: 0.5369 - accuracy: 0.7396 - 961ms/epoch - 1ms/step
Epoch 81/100
804/804 - 1s - loss: 0.5367 - accuracy: 0.7399 - 1s/epoch - 1ms/step
Epoch 82/100
804/804 - 1s - loss: 0.5369 - accuracy: 0.7404 - 980ms/epoch - 1ms/step
Epoch 83/100
804/804 - 1s - loss: 0.5365 - accuracy: 0.7399 - 965ms/epoch - 1ms/step
Epoch 84/100
804/804 - 1s - loss: 0.5365 - accuracy: 0.7407 - 1s/epoch - 1ms/step
Epoch 85/100
804/804 - 1s - loss: 0.5366 - accuracy: 0.7396 - 973ms/epoch - 1ms/step
Epoch 86/100
804/804 - 1s - loss: 0.5364 - accuracy: 0.7401 - 1s/epoch - 1ms/step
Epoch 87/100
804/804 - 1s - loss: 0.5361 - accuracy: 0.7405 - 1s/epoch - 1ms/step
Epoch 88/100
804/804 - 1s - loss: 0.5359 - accuracy: 0.7394 - 977ms/epoch - 1ms/step
Epoch 89/100
804/804 - 1s - loss: 0.5360 - accuracy: 0.7393 - 1s/epoch - 1ms/step
Epoch 90/100
804/804 - 1s - loss: 0.5365 - accuracy: 0.7406 - 1s/epoch - 1ms/step
Epoch 91/100
804/804 - 1s - loss: 0.5363 - accuracy: 0.7402 - 982ms/epoch - 1ms/step
Epoch 92/100
804/804 - 1s - loss: 0.5361 - accuracy: 0.7403 - 956ms/epoch - 1ms/step
Epoch 93/100
804/804 - 1s - loss: 0.5359 - accuracy: 0.7400 - 996ms/epoch - 1ms/step
Epoch 94/100
804/804 - 1s - loss: 0.5363 - accuracy: 0.7403 - 1s/epoch - 1ms/step
Epoch 95/100
804/804 - 1s - loss: 0.5360 - accuracy: 0.7401 - 1s/epoch - 1ms/step
Epoch 96/100
804/804 - 1s - loss: 0.5357 - accuracy: 0.7402 - 952ms/epoch - 1ms/step
Epoch 97/100
804/804 - 1s - loss: 0.5356 - accuracy: 0.7398 - 974ms/epoch - 1ms/step
Epoch 98/100
804/804 - 1s - loss: 0.5355 - accuracy: 0.7400 - 1s/epoch - 1ms/step
Epoch 99/100
804/804 - 1s - loss: 0.5355 - accuracy: 0.7406 - 1s/epoch - 1ms/step
Epoch 100/100
804/804 - 1s - loss: 0.5358 - accuracy: 0.7407 - 1s/epoch - 2ms/step

In [15]:
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5556 - accuracy: 0.7294 - 483ms/epoch - 2ms/step
Loss: 0.5555561780929565, Accuracy: 0.7294460535049438

In [16]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")